<a href="https://colab.research.google.com/github/pedrociancaglini/ds_coder/blob/main/5_Pandas_Practicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [6]:
Numeros = range(50, 70, 2)
Numeros_series = pd.Series(Numeros)
print(Numeros_series)

0    50
1    52
2    54
3    56
4    58
5    60
6    62
7    64
8    66
9    68
dtype: int64


In [8]:
print(Numeros_series[2])

54


In [10]:
print(Numeros_series.index)

RangeIndex(start=0, stop=10, step=1)


In [12]:
print(Numeros_series.values)

[50 52 54 56 58 60 62 64 66 68]


In [14]:
Numeros_en_texto = ['primero','segundo','tercero','cuarto','quinto','sexto','septimo','octavo','noveno','decimo',]
Numeros_serie_2 = pd.Series(Numeros, index=Numeros_en_texto)
print(Numeros_serie_2)

primero    50
segundo    52
tercero    54
cuarto     56
quinto     58
sexto      60
septimo    62
octavo     64
noveno     66
decimo     68
dtype: int64


In [16]:
modelos = ['A4 3.0 Quattro 4dr manual', 'A4 3.0 Quattro 4dr auto', 'A6 3.0 4dr', 'A6 3.0 Quattro 4dr', 'A4 3.0 convertible 2dr']
peso = [3583, 3627, 3561, 3880, 3814]
precios = ['$33,430', '$34,480', '$36,640', '$39,640', '$42,490']

In [18]:
Autos_peso = pd.Series(peso,index=modelos)
Autos_precio = pd.Series(precios,index=modelos)

In [20]:
print(Autos_precio)

A4 3.0 Quattro 4dr manual    $33,430
A4 3.0 Quattro 4dr auto      $34,480
A6 3.0 4dr                   $36,640
A6 3.0 Quattro 4dr           $39,640
A4 3.0 convertible 2dr       $42,490
dtype: object


In [22]:
print(Autos_peso)

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
dtype: int64


In [24]:
Autos = pd.DataFrame({'Peso':Autos_peso,'Precio':Autos_precio})
Autos

Peso   Precio
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [26]:
# Playing with Chess
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_df = pd.DataFrame(Ajedrez_64, columns=range(1,9), index=['A','B','C','D','E','F','G','H']) 
Ajedrez_df


1   2   3   4   5   6   7   8
A   1   2   3   4   5   6   7   8
B   9  10  11  12  13  14  15  16
C  17  18  19  20  21  22  23  24
D  25  26  27  28  29  30  31  32
E  33  34  35  36  37  38  39  40
F  41  42  43  44  45  46  47  48
G  49  50  51  52  53  54  55  56
H  57  58  59  60  61  62  63  64

**Seleccion de elementos**

In [29]:
# Mediante Indice
Numeros_serie_2['quinto']

58

In [31]:
# Mediante el metodo loc()
Numeros_serie_2.loc['quinto']

58

In [34]:
# Mediante el metodo iloc()
# Solo para indices numericos
Numeros_serie_2.iloc[4]

58

**Seleccionando un Data Frame**

In [35]:
# Tambien podemos seleccionar partes especificas del Data Frame como columnas, indices y valores
Autos.index

Index(['A4 3.0 Quattro 4dr manual', 'A4 3.0 Quattro 4dr auto', 'A6 3.0 4dr',
       'A6 3.0 Quattro 4dr', 'A4 3.0 convertible 2dr'],
      dtype='object')

In [37]:
Autos.columns

Index(['Peso', 'Precio'], dtype='object')

In [38]:
Autos.values

array([[3583, '$33,430'],
       [3627, '$34,480'],
       [3561, '$36,640'],
       [3880, '$39,640'],
       [3814, '$42,490']], dtype=object)

In [40]:
# Seleccion de columna
Autos['Peso']

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
Name: Peso, dtype: int64

In [42]:
# Seleccion de fila
Autos.values[1]

array([3627, '$34,480'], dtype=object)

In [44]:
Autos.loc['A4 3.0 Quattro 4dr auto']

Peso         3627
Precio    $34,480
Name: A4 3.0 Quattro 4dr auto, dtype: object

In [47]:
# Seleccionando con una condicion
Autos.loc[Autos.Peso >= 3600, 'Precio']

A4 3.0 Quattro 4dr auto    $34,480
A6 3.0 Quattro 4dr         $39,640
A4 3.0 convertible 2dr     $42,490
Name: Precio, dtype: object

**Operaciones Basicas con Datos en Pandas**

In [48]:
# Transposicion
Autos.T

A4 3.0 Quattro 4dr manual A4 3.0 Quattro 4dr auto A6 3.0 4dr  \
Peso                        3583                    3627       3561   
Precio                   $33,430                 $34,480    $36,640   

       A6 3.0 Quattro 4dr A4 3.0 convertible 2dr  
Peso                 3880                   3814  
Precio            $39,640                $42,490

In [50]:
# Funciones Vectorizadas
## Las funciones vectorizadas o ufunc de numpy pueden realizarse tambien sobre Data Frames y Series
## Tras ejecutar la operacion, se conservan los indices
Numeros_3 = range(51,70,2)
Numeros_serie_3 = pd.Series(Numeros_3, index=Numeros_en_texto)
Numeros_serie_3

primero    51
segundo    53
tercero    55
cuarto     57
quinto     59
sexto      61
septimo    63
octavo     65
noveno     67
decimo     69
dtype: int64

In [51]:
largo = [179, 179, 192, 192, 180]
Autos_2 = pd.DataFrame({'Peso':peso,'Largo':largo},index=modelos)
Autos_2

Peso  Largo
A4 3.0 Quattro 4dr manual  3583    179
A4 3.0 Quattro 4dr auto    3627    179
A6 3.0 4dr                 3561    192
A6 3.0 Quattro 4dr         3880    192
A4 3.0 convertible 2dr     3814    180

In [52]:
Autos_2 / Autos_2.iloc[0] * 100

Peso       Largo
A4 3.0 Quattro 4dr manual  100.000000  100.000000
A4 3.0 Quattro 4dr auto    101.228021  100.000000
A6 3.0 4dr                  99.385989  107.262570
A6 3.0 Quattro 4dr         108.289143  107.262570
A4 3.0 convertible 2dr     106.447111  100.558659

In [53]:
# Conservacion de los indices
Numeros_serie_2

primero    50
segundo    52
tercero    54
cuarto     56
quinto     58
sexto      60
septimo    62
octavo     64
noveno     66
decimo     68
dtype: int64

In [54]:
Numeros_serie_2 + Numeros_serie_3

primero    101
segundo    105
tercero    109
cuarto     113
quinto     117
sexto      121
septimo    125
octavo     129
noveno     133
decimo     137
dtype: int64

In [55]:
Numeros_serie_2.add(Numeros_serie_3)

primero    101
segundo    105
tercero    109
cuarto     113
quinto     117
sexto      121
septimo    125
octavo     129
noveno     133
decimo     137
dtype: int64

In [56]:
# Conservacion de los indices
Numeros_serie_2_porcion = Numeros_serie_2[4:7]
Numeros_serie_3_porcion = Numeros_serie_3[5:8]
print(Numeros_serie_3_porcion, Numeros_serie_2_porcion)

sexto      61
septimo    63
octavo     65
dtype: int64 quinto     58
sexto      60
septimo    62
dtype: int64


In [57]:
# Los indices que no coinciden, se rellenan con NaN
print(Numeros_serie_2_porcion + Numeros_serie_3_porcion)

octavo       NaN
quinto       NaN
septimo    125.0
sexto      121.0
dtype: float64


**Lidiando con valores faltantes**

In [58]:
# La mayoria de las operaciones en Pandas, admiten un parametro 'fill_value', que indica el valor a inserar en caso de resultar un NaN
Numeros_serie_2_porcion.add(Numeros_serie_3_porcion, fill_value = 0)

octavo      65.0
quinto      58.0
septimo    125.0
sexto      121.0
dtype: float64

In [59]:
valor_nan = np.nan
type(valor_nan)

float

In [60]:
2 * valor_nan

nan

In [61]:
np.nanprod([2,valor_nan])

2.0

**Trabajando con Datos Ausentes**

In [66]:
Numeros_nan = Numeros_serie_2_porcion + Numeros_serie_3_porcion
Numeros_nan

octavo       NaN
quinto       NaN
septimo    125.0
sexto      121.0
dtype: float64

In [67]:
# Podemos Marcarlos
Numeros_nan.isnull()

octavo      True
quinto      True
septimo    False
sexto      False
dtype: bool

In [68]:
# Podemos Reemplazarlos
Numeros_nan.fillna(0)

octavo       0.0
quinto       0.0
septimo    125.0
sexto      121.0
dtype: float64

In [69]:
# Podemos Eliminarlos 
Numeros_nan.dropna()

septimo    125.0
sexto      121.0
dtype: float64

# Resumen
Nociones básicas de Pandas: 
Data Wrangling y Pandas 
Las estructuras de datos en Pandas 
Selección de elementos
Operaciones básicas con datos en Pandas
